### ISSUE TITLE
Оценка проекта (74/100)

### ISSUE THREAD

**Issue by structxz** [sp-va/web_calculator#1]
В целом все сделано четко и без особых ошибок. Но есть моменты, которые стоит подметить.

1. Нету никаких тестов. Поэтому пришлось поставить 0 баллов.
2. Ошибки обрабатываются не совсем верно. Например, если отправить запрос с выражением "2+" выдается код 500 и в ошибке сказано, что это ошибка сервера, что неверно, так как это ошибка клиента, который отправил неверное выр-е, в данном случае должен быть код 400 и ошибка "invalid expression" (как вариант). Такая же проблема с делением на 0 и другими ошибками. Поэтому поставил 15/20.
3. За качество кода поставил 19/20, потому что возможно было бы лучше, если были где-то коментарии. Но это мое субъективное мнение, поэтому снял только 1 балл. Ну и это точно не идеальный код (хотя все может быть).

В общем были бы тесты и чуть-чуть по красивие  и подробно был написан README файл, то было бы шикарно.

**Comment by sp-va** [comment]
Спасибо за уделённое на проверку время ;)
